services:
    web:
        image: nginx:latest
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=spark.localhost
        volumes:
            - .:/var/www/html
            - ./docker/web/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
            nginx-proxy:

    php:
        image: php-fpm:latest
        build: docker/build/php-fpm
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "8080:8080"
        networks:
            default:

    mysql:
        ports:
            - "2345:3306"
        image: mysql:latest
        command: --mysql-native-password=ON  --log-bin-trust-function-creators=1
        working_dir: /tmp/proj
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - spark_db:/var/lib/mysql
            - ./docker/local:/tmp/proj
        networks:
            - default
    redis:
        image: redis
        networks:
            - default

    node:
        image: node:spark
        build: docker/build/npm
        user: node
        working_dir: /var/www/html
        ports:
          - "5173:5173"
        volumes:
          - .:/var/www/html

volumes:
    spark_db:

networks:
    default:
    nginx-proxy:
        external: true
